.POSIX:

OBJS=src/uri.o \
	 src/keyval.o

CFLAGS += -Iinclude

all: librequests.a

.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

librequests.so: $(OBJS)
	$(CC) $(LDFLAGS) -shared -o $@ $(OBJS)

librequests.a: $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	rm -f $(OBJS) librequests.so librequests.a

